version: "3"

services:

  db:
    build: db
    read_only: true
    restart: unless-stopped
    volumes:
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
    # Uncomment the following to enable backup:
    # - AWS_ACCESS_KEY_ID=XXXX
    # - AWS_SECRET_ACCESS_KEY=XXXX
    # - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
    # - AWS_REGION=us-east-1

  app:
    build:
      context: app
      # Uncomment below to use Team Edition or customize UID/GID:
      # args:
      #   - edition=team
      #   - PUID=1000
      #   - PGID=1000
      #   - MM_VERSION=5.31
    restart: unless-stopped
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      - ./volumes/app/mattermost/plugins:/mattermost/plugins:rw
      - ./volumes/app/mattermost/client-plugins:/mattermost/client/plugins:rw
      - /etc/localtime:/etc/localtime:ro
      # To use GitLab SSO, add GitLab PKI chain inside Alpine:
      # - <path_to_your_gitlab_pki>/pki_chain.pem:/etc/ssl/certs/pki_chain.pem:ro
    environment:
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:mmuser_password@db:5432/mattermost?sslmode=disable&connect_timeout=10
      # Optional custom config path:
      # - MM_CONFIG=/mattermost/config/config.json

  web:
    build: web
    ports:
      - "80:8080"
      - "443:8443"
    read_only: true
    restart: unless-stopped
    volumes:
      - ./volumes/web/cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro
    cap_drop:
      - ALL
